# Generated by Django 4.2.23 on 2025-08-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_insights', to=settings.AUTH_USER_MODEL),
        ),
    ]
