# Generated by Django 4.2.23 on 2025-08-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryanalytics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='transactions.category'),
        ),
        migrations.AddField(
            model_name='categoryanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='financialsnapshot',
            unique_together={('user', 'snapshot_type', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryanalytics',
            unique_together={('user', 'category', 'analysis_month')},
        ),
    ]
