# Generated by Django 4.2.23 on 2025-08-04 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goalcategory',
            options={'verbose_name': 'Goal Category', 'verbose_name_plural': 'Goal Categories'},
        ),
        migrations.AlterModelOptions(
            name='goalcontribution',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goalmilestone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='goaltemplate',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='goalcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='goalmilestone',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='auto_contribution_amount',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='auto_contribution_frequency',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_image',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='milestone_notifications',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='goalcontribution',
            name='contribution_date',
        ),
        migrations.RemoveField(
            model_name='goalcontribution',
            name='contribution_type',
        ),
        migrations.RemoveField(
            model_name='goaltemplate',
            name='default_duration_months',
        ),
        migrations.RemoveField(
            model_name='goaltemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='goaltemplate',
            name='template_data',
        ),
        migrations.AddField(
            model_name='goal',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goal',
            name='contribution_frequency',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='goalcategory',
            name='is_system_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='suggested_duration_days',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='auto_contribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(default='savings', max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_extended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goalcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goalcontribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goalcontribution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='achieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='target_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='default_target_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='goal_type',
            field=models.CharField(default='savings', max_length=100),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='is_system_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goaltemplate',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='goal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goalcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goalcontribution',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goalmilestone',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goaltemplate',
            table=None,
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='goalmilestone',
            name='reward_description',
        ),
        migrations.RemoveField(
            model_name='goalmilestone',
            name='target_amount',
        ),
        migrations.RemoveField(
            model_name='goalmilestone',
            name='updated_at',
        ),
    ]
